
import java.awt.Toolkit;

/**
 * Class        CrapSimAboutForm.java
 * File         CrapSimAboutForm.java
 * Description  displays the about form with information about PSE program and a close button
 * Environment  PC, Windows 8, JDK 8.1
 * History log 
 * @author      Evan Wansa
 * 02/15/2017
 * Version      1.0.0
 * @see         javax.swing.JDialog 
 * Project 3
 * Due date: 03/09/2017
 */
public class CrapSimAboutForm extends javax.swing.JDialog {

    /**
     * Creates new form CrapSimAboutForm
     */
    public CrapSimAboutForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Sets the form title
        this.setTitle("Crap Simulation About Form");
        
        //Centers the form at start.
        setLocationRelativeTo(null);
        
        //Sets icon for form
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage("src/Images/Icon.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbout = new javax.swing.JPanel();
        productversionJLabel = new javax.swing.JLabel();
        versionJLabel = new javax.swing.JLabel();
        vendorJLabel = new javax.swing.JLabel();
        evanJLabel = new javax.swing.JLabel();
        contactJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        redDieJLabel = new javax.swing.JLabel();
        scrollpaneAbout = new javax.swing.JScrollPane();
        txtAreaAbout = new javax.swing.JTextArea();
        okJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelAbout.setLayout(new java.awt.GridLayout(3, 0, 0, 2));

        productversionJLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        productversionJLabel.setText("Product Version:");
        panelAbout.add(productversionJLabel);

        versionJLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        versionJLabel.setText("1.0");
        panelAbout.add(versionJLabel);

        vendorJLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vendorJLabel.setText("Vendor:");
        panelAbout.add(vendorJLabel);

        evanJLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        evanJLabel.setText("Evan Wansa");
        panelAbout.add(evanJLabel);

        contactJLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contactJLabel.setText("Contact");
        panelAbout.add(contactJLabel);

        emailJLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emailJLabel.setText("e.wansa7628@edmail.edu");
        panelAbout.add(emailJLabel);

        redDieJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dice2.gif"))); // NOI18N

        txtAreaAbout.setEditable(false);
        txtAreaAbout.setColumns(20);
        txtAreaAbout.setLineWrap(true);
        txtAreaAbout.setRows(5);
        txtAreaAbout.setText("* A player rolls two dice.Each dice has six faces.\n* These faces contain six sides of a die.  \n* After the dice have come to rest, the sum of the spots shown is calculated \n* If the sum is 7 or 11 on the first throw, the player wins. \n* If the sum is 2, 3 or 12 on the first throw, the player loses (craps). \n* If the sum is 4, 5, 6, 8, 9 or 10 on the first throw,that sum becomes the player’s “point.” \n* To win, you must continue rolling the dice until you get the \"point\" from your first roll\n* The player loses by rolling a 7 before making the point.");
        scrollpaneAbout.setViewportView(txtAreaAbout);

        okJButton.setText("OK");
        okJButton.setToolTipText("Close Window");
        okJButton.setSelected(true);
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redDieJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollpaneAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(201, 201, 201)
                    .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redDieJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpaneAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        //Close About Form
        this.dispose();
    }//GEN-LAST:event_okJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrapSimAboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrapSimAboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrapSimAboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrapSimAboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrapSimAboutForm dialog = new CrapSimAboutForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JLabel evanJLabel;
    private javax.swing.JButton okJButton;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JLabel productversionJLabel;
    private javax.swing.JLabel redDieJLabel;
    private javax.swing.JScrollPane scrollpaneAbout;
    private javax.swing.JTextArea txtAreaAbout;
    private javax.swing.JLabel vendorJLabel;
    private javax.swing.JLabel versionJLabel;
    // End of variables declaration//GEN-END:variables
}
